name: minimal_weather
description: A simple weather app by MetaWeather API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.1.0
  hydrated_bloc: ^7.1.0
  intl: ^0.17.0
  json_annotation: ^4.0.0
  lottie: ^1.2.1
  path_provider: ^2.0.3
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  bloc_test: ^8.1.0
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter
  json_serializable: ^4.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/condition_lotties/
    - assets/states/
