name: minimal_weather
description: A simple weather app by MetaWeather API
version: 1.0.1+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.1
  hydrated_bloc: ^9.0.0
  intl: ^0.17.0
  json_annotation: ^4.0.0
  lottie: ^2.2.0
  # test
  open_meteo_api:
    path: packages/open_meteo_api
  path_provider: ^2.0.3
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  bloc_test: ^9.0.1
  build_runner: ^2.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  # test: ^1.21.6
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/condition_lotties/
    - assets/states/
